import { cn } from '@/lib/utils';

/**
 * Texas Solutions logo: the grey chevron mark with the TEXAS SOLUTIONS
 * wordmark, the same artwork used on dispatch.texassolutions.co.
 * Files live in public/brand and are generated by scripts/brand-assets.py
 * (which also writes the favicons and the Open Graph image).
 */

const LOGO_SRC = '/brand/texas-solutions-logo.png'; // 480 x 166
const ICON_SRC = '/brand/texas-solutions-icon.png'; // 105 x 128

/** The chevron mark on its own (used where space is tight). */
export function LogoMark({ className, title }: { className?: string; title?: string }) {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={ICON_SRC}
      width={105}
      height={128}
      alt={title ?? ''}
      aria-hidden={title ? undefined : true}
      className={cn('h-10 w-auto shrink-0', className)}
    />
  );
}

/** Full logo. With showWordmark false (or hidden by wordmarkClassName on small screens) only the mark shows. */
export function Logo({
  className,
  size = 'md',
  showWordmark = true,
  wordmarkClassName,
}: {
  className?: string;
  size?: 'sm' | 'md' | 'lg';
  showWordmark?: boolean;
  wordmarkClassName?: string;
}) {
  const height = size === 'sm' ? 'h-9' : size === 'lg' ? 'h-14' : 'h-11';

  return (
    <span className={cn('inline-flex items-center', className)}>
      {showWordmark && (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={LOGO_SRC}
          width={480}
          height={166}
          alt="Texas Solutions"
          className={cn('w-auto', height, wordmarkClassName)}
        />
      )}
      {/* Mark-only fallback when the full logo is hidden on narrow screens. */}
      {(!showWordmark || wordmarkClassName) && (
        <LogoMark
          className={cn(height, showWordmark && wordmarkClassName ? markOnlyWhenHidden(wordmarkClassName) : '')}
        />
      )}
    </span>
  );
}

/**
 * The header passes wordmarkClassName="hidden min-[520px]:flex" to hide the
 * wordmark on phones. The mark-only image takes the opposite visibility.
 */
function markOnlyWhenHidden(wordmarkClassName: string) {
  // Literal class names so Tailwind generates them.
  if (wordmarkClassName.includes('min-[520px]:')) return 'min-[520px]:hidden';
  if (wordmarkClassName.includes('sm:')) return 'sm:hidden';
  if (wordmarkClassName.includes('md:')) return 'md:hidden';
  return 'hidden';
}
